/* eslint-disable */
// @ts-nocheck
import { createFileRoute, Link } from '@tanstack/react-router'
import { useState } from 'react'
import { highlight } from '../lib'
import { HOME_SEO } from '../content'
import { Icon, DemoPlayer, useHead } from '../ui'

export const Route = createFileRoute('/')({ component: Home })

const Code = ({ src, lang }: { src: string; lang?: string }) => (
  <pre data-lang={lang}><code dangerouslySetInnerHTML={{ __html: highlight(src, lang) }} /></pre>
)

const SNIPPETS = {
  config: `import { defineConfig } from 'kernelcms'
import { sqliteAdapter } from 'kernelcms/sqlite'

export default defineConfig({
  secret: process.env.KERNEL_SECRET,
  db: sqliteAdapter({ url: 'file:./content.db' }),
  collections: [
    { slug: 'users', auth: true,
      fields: [{ name: 'name', type: 'text' }] },
    { slug: 'posts',
      access: { read: () => true },
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'richText' },
        { name: 'author', type: 'relationship', relationTo: 'users' },
      ] },
  ],
})`,
  rest: `# Auto-generated REST, filtered + paginated + access-checked
GET /api/posts?where[status][equals]=published&sort=-createdAt&depth=1

{
  "docs": [
    { "id": "p_01", "title": "Hello", "author": { "name": "Ada" } }
  ],
  "totalDocs": 1,
  "page": 1
}`,
  local: `// The same operations in-process, fully typed, no HTTP hop
const post = await kernel.local.create({
  collection: 'posts',
  data: { title: 'Hello', body: '…', author: ada.id },
})

const list = await kernel.local.find({
  collection: 'posts',
  where: { status: { equals: 'published' } },
})`,
}

const MODULE = `export const comments = defineModule({
  name: 'comments',
  version: '1.0.0',
  collections: [
    { slug: 'comments', access: { read: () => true },
      fields: [/* … */] },
  ],
  endpoints: [
    defineEndpoint({
      method: 'POST', path: '/comments/:postId',
      access, handler,
    }),
  ],
  jobs: [{ slug: 'moderate-comments', handler }],
})`

const SPECS = [
  ['01', 'Config as code', 'Collections, globals, and 20+ field types in TypeScript, with end-to-end type inference.'],
  ['02', 'REST, GraphQL & a typed API', 'REST, GraphQL, and a typed in-process Local API from one model - identical operations and access rules.'],
  ['03', 'Swappable adapters', 'Database, storage, auth, email, cache, and search are swappable adapters. The core stays tiny.'],
  ['04', 'Secure by default', 'Deny-by-default access, row-level filters, field redaction, and a privilege-escalation guard.'],
  ['05', 'Migrations you trust', 'Diff-based, additive, deterministic. Preview every change before it touches the database.'],
  ['06', 'Built to extend', 'Typed endpoints, feature modules, background jobs, and custom admin components.'],
]

const COMPARE = [
  ['Framework coupling', 'None - web-standard Request → Response', 'Often welded to one framework'],
  ['Default database', 'SQLite via node:sqlite, zero native deps', 'Mongo or Postgres, heavier setup'],
  ['Install & cold start', 'Light and fast', 'Large dependency tree, slow boots'],
  ['Dev loop', 'npx kernel dev + inlined admin', 'A full framework build pipeline'],
  ['Migrations', 'Diff-based, risk-classified, deterministic', 'Frequently a pain point'],
  ['Deploy', 'One container, anywhere', 'Often tied to one host shape'],
  ['Heavy features', 'Optional adapters; core stays tiny', 'Batteries baked into the core'],
]

const scrollToId = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' })

function Home() {
  useHead(HOME_SEO.title, HOME_SEO.description)
  const [tab, setTab] = useState('config')
  const langs = { config: 'ts', rest: 'http', local: 'ts' }
  return (
    <main>
      <section className="hero2"><div className="wrap hero2-grid">
        <div className="hero2-text">
          <p className="mono-eyebrow"><span className="c">//</span> backend &amp; cms for any website</p>
          <h1>Add a backend to your website. <span style={{ color: 'var(--muted)' }}>No code required.</span></h1>
          <p className="hero2-sub">KernelCMS gives any site - even one generated by AI with v0, Lovable, Bolt, or Cursor - a database, an API, and a no-code admin to edit it. Open-source, self-hosted, and ready in minutes.</p>
          <div className="hero2-actions">
            <Link className="btn primary" to="/guides/$slug" params={{ slug: 'add-a-backend-to-any-site' }}><Icon name="bolt" /> Add a backend</Link>
            <button className="btn ghost" onClick={() => scrollToId('watch')}><Icon name="play" /> Watch the demo</button>
          </div>
          <p className="hero2-meta">Open-source (MIT) · TypeScript · works with any frontend or AI-generated site</p>
        </div>
        <div className="hero2-code">
          <DemoPlayer url="localhost:3000/admin" caption="See how easy it is" base="demo" autoplay />
        </div>
      </div></section>

      <section className="section" style={{ paddingBlock: 'clamp(28px,4vw,52px)' }}><div className="wrap">
        <div className="lead-head"><p className="mono-eyebrow"><span className="c">//</span> how it works</p><h2>From a hardcoded page to fully editable, in three steps.</h2></div>
        <div className="steps">
          {[
            ['1', 'Describe your content', 'List what is on your page - headings, text, images, and lists like posts or products - in one config file. Or let your AI assistant do it for you.'],
            ['2', 'Get an API and an admin', 'KernelCMS instantly builds a database, a REST and GraphQL API, and a polished admin panel from that description. No backend to write.'],
            ['3', 'Edit with no code', 'You and your team edit content live in the admin, with preview. Your site reads it from the API. No redeploys to change a word.'],
          ].map(([n, t, d], i, a) => (
            <div className="step" key={n}><div className="step-n">{n}</div><h3>{t}</h3><p>{d}</p>{i < a.length - 1 && <span className="step-arrow"><Icon name="arrow" /></span>}</div>
          ))}
        </div>
      </div></section>

      <section className="section" id="watch" style={{ paddingTop: 'clamp(20px,3vw,36px)' }}><div className="wrap" style={{ maxWidth: 1040 }}>
        <div className="lead-head" style={{ textAlign: 'center', marginInline: 'auto' }}><p className="mono-eyebrow"><span className="c">//</span> watch the walkthrough</p><h2>See a real site get a backend in minutes.</h2></div>
        <DemoPlayer url="kernelcms.com · full walkthrough" caption="Watch the full walkthrough" base="walkthrough" />
      </div></section>

      <section className="section"><div className="wrap">
        <div className="showcase">
          <div>
            <p className="mono-eyebrow"><span className="c">//</span> for developers</p>
            <h2 style={{ fontSize: 'clamp(1.6rem,1.1rem+1.8vw,2.3rem)', fontWeight: 600, margin: '12px 0 0', letterSpacing: '-.025em' }}>Prefer code? One typed config, three APIs.</h2>
            <p style={{ color: 'var(--muted)', fontSize: 16, margin: '16px 0 0', maxWidth: '52ch' }}>Define your model in <code>kernel.config.ts</code> and get REST, GraphQL, and a typed in-process Local API over the same access rules, with end-to-end TypeScript inference.</p>
            <div className="hero2-actions" style={{ marginTop: 24 }}>
              <Link className="btn primary" to="/docs/$slug" params={{ slug: 'quickstart' }}><Icon name="terminal" /> Quickstart</Link>
              <Link className="btn ghost" to="/docs">Read the docs <Icon name="arrow" /></Link>
            </div>
          </div>
          <div className="code">
            <div className="code-tabs"><div className="code-dots"><span className="code-dot" /><span className="code-dot" /><span className="code-dot" /></div>
              {['config', 'rest', 'local'].map((id) => (
                <button key={id} className={`code-tab${tab === id ? ' active' : ''}`} onClick={() => setTab(id)}>{id === 'config' ? 'kernel.config.ts' : id === 'rest' ? 'REST' : 'Local API'}</button>
              ))}
            </div>
            <div className="code-body"><Code src={SNIPPETS[tab]} lang={langs[tab]} /></div>
          </div>
        </div>
      </div></section>

      <section className="section" style={{ paddingTop: 0 }}><div className="wrap">
        <div className="lead-head"><p className="mono-eyebrow"><span className="c">//</span> built for the whole team</p><h2>Code stays code. Content stays editable.</h2><p>Developers own the model in typed config, versioned in git. Editors change pages, copy, and media in a polished no-code admin with live preview and a page builder.</p></div>
        <div className="duo">
          <div className="duo-panel"><span className="k">// for developers</span><h3>Lives in code</h3><ul>
            <li><Icon name="check" /> The content model in a typed <code>kernel.config.ts</code></li>
            <li><Icon name="check" /> Access rules, hooks, and computed fields</li>
            <li><Icon name="check" /> Deterministic migrations, reviewed in pull requests</li>
            <li><Icon name="check" /> End-to-end type inference and a typed client</li>
          </ul></div>
          <div className="duo-panel"><span className="k">// for editors</span><h3>Stays no-code</h3><ul>
            <li><Icon name="check" /> Edit pages, copy, and media with zero code</li>
            <li><Icon name="check" /> A blocks page builder for layouts</li>
            <li><Icon name="check" /> Live preview as you type</li>
            <li><Icon name="check" /> Drafts, version history, and scheduled publish</li>
          </ul></div>
        </div>
      </div></section>

      <section className="section"><div className="wrap">
        <div className="lead-head"><p className="mono-eyebrow"><span className="c">//</span> what you get</p><h2>One config file. Your whole headless CMS backend, generated.</h2></div>
        <div className="specs">
          {SPECS.map(([n, t, d]) => <div className="spec" key={n}><span className="n">{n}</span><h3>{t}</h3><p>{d}</p></div>)}
        </div>
      </div></section>

      <section className="section"><div className="wrap">
        <div className="showcase">
          <div className="code">
            <div className="code-tabs"><div className="code-dots"><span className="code-dot" /><span className="code-dot" /><span className="code-dot" /></div><span className="code-tab active">comments.module.ts</span></div>
            <div className="code-body"><Code src={MODULE} lang="ts" /></div>
          </div>
          <div>
            <p className="mono-eyebrow"><span className="c">//</span> build your own</p>
            <h2 style={{ fontSize: 'clamp(1.6rem,1.1rem+1.8vw,2.3rem)', fontWeight: 600, margin: '12px 0 0', letterSpacing: '-.025em' }}>When CRUD isn't enough, you don't drop down a layer.</h2>
            <p style={{ color: 'var(--muted)', fontSize: 16, margin: '16px 0 0', maxWidth: '52ch' }}>Add typed endpoints, computed fields, and whole feature modules - a collection, endpoints, and jobs bundled into one conflict-checked unit. Same access pipeline, same validation, auto-documented.</p>
            <div className="hero2-actions" style={{ marginTop: 24 }}>
              <Link className="btn" to="/docs/$slug" params={{ slug: 'modules' }}>Modules <Icon name="arrow" /></Link>
              <Link className="btn ghost" to="/docs/$slug" params={{ slug: 'custom-endpoints' }}>Custom endpoints</Link>
            </div>
          </div>
        </div>
      </div></section>

      <section className="section" style={{ paddingTop: 'clamp(40px,6vw,72px)' }}><div className="wrap">
        <div className="lead-head"><p className="mono-eyebrow"><span className="c">//</span> how it compares</p><h2>Most headless CMSs make you adopt their whole world.</h2><p>KernelCMS doesn't. Here is the difference, line by line.</p></div>
        <table className="compare"><thead><tr><th></th><th className="us">KernelCMS</th><th>Typical heavyweight CMS</th></tr></thead><tbody>
          {COMPARE.map(([dim, us, them]) => (
            <tr key={dim}><td>{dim}</td><td className="us-col"><span className="chk yes"><Icon name="check" /> {us}</span></td><td className="meh">{them}</td></tr>
          ))}
        </tbody></table>
        <div className="closer">
          <div className="closer-text"><h2>Ready in three steps.</h2><p>Install, write a config, run <code style={{ fontFamily: 'var(--mono)', fontSize: '.85em' }}>npx kernel dev</code>.</p></div>
          <div className="hero2-actions">
            <Link className="btn primary" to="/docs/$slug" params={{ slug: 'quickstart' }}>Read the quickstart</Link>
            <a className="btn ghost" href="https://github.com/RobbinPilhede/KernelCMS" target="_blank" rel="noopener"><Icon name="github" /> GitHub</a>
          </div>
        </div>
      </div></section>
    </main>
  )
}
